### ISSUE TITLE
Idea of using API instead of hardcoded data

### ISSUE THREAD

**Issue by max-programming** [BraydenTW/react-emoji-search#17]
Hi! I saw this is an amazing project! I think it would be better to use an API that provides emojis. Because, not all emojis are available in the `data.json` file.
I have used a simple and great API. [OpenEmoji](https://emoji-api.com/).

**Comment by diogo405** [comment]
Yeah, it would be great if they included the search keywords for each emoji in this method response:
https://emoji-api.com/emojis?access_key=123412341234

Otherwise, we gonna need to call the search endpoint every time the search input changes :/

**Comment by max-programming** [comment]
There won't be any load if we call the search endpoint onChange

**Comment by diogo405** [comment]
Yeah... Might be good to give it go. If it's not slow and provides good results I would switch to the API 👍

**Comment by max-programming** [comment]
@diogo405 @BraydenTW I have actually made an emoji app. It's simple with Vanilla JS: https://maxmojis.netlify.app Using this API

**Comment by BraydenTW** [comment]
Very cool @max-programming! So you used the OpenEmoji API?

**Comment by max-programming** [comment]
> Very cool @max-programming! So you used the OpenEmoji API?

Yes. I used that one

**Comment by BraydenTW** [comment]
Sounds good. However if we want to use that API or any other one, we would have breaking changes in the code. It is doable, but we would have to change the values in the JavaScript. Another reason why this wouldn't be the best solution is because the JSON file I am using right now has the best keywords. I've tried other APIs but they have not been great 😞

However if you think it would work well, feel free to submit a PR with the new Fetch API command and update the values in the code.

**Comment by max-programming** [comment]
I am thinking of working on it. I will make a PR if I will be successful!

**Comment by BraydenTW** [comment]
Sounds good!

**Comment by max-programming** [comment]
@BraydenTW Can you please enter your email on this site and send the API key?

https://emoji-api.com/

Delete the comment with the API key when I send another msg

**Comment by BraydenTW** [comment]
@max-programming, here you go: ** 9a78c87d40e81208b762e6e035a28e48a01e77e1**

**Comment by max-programming** [comment]
Got it! Delete that now if you want 😉

**Comment by BraydenTW** [comment]
😁👍

**Comment by BraydenTW** [comment]
@max-programming , how is the new api going?

**Comment by max-programming** [comment]
Yeah I integrated the API with it. But I think the **instant search** will not be able to work if we make request to the API every now and then. So I will try adding the functionality of custom search after fetching all the emojis at once. I will be at a holiday for next couple of weeks

**Comment by BraydenTW** [comment]
Okay no problem. 👋

**Comment by max-programming** [comment]
@BraydenTW I think I am unsuccessful in doing this as of now because I have a lot of pressure about my exams. I will keep this issue open and try to work on it whenever I get time

**Comment by BraydenTW** [comment]
@max-programming, no problem at all. Take the time you need to do well on those exams. (They’re important 👍)

Feel free to pick back up on this whenever you can.

**Comment by max-programming** [comment]
Thanks!

**Comment by BraydenTW** [comment]
@max-programming , it’s been a bit. If you got other obligations right now, that’s ok. I’ll close the issue for now.
