### ISSUE TITLE
Dark mode toggle button

### ISSUE THREAD

**Issue by SubhamKarmakar24** [BraydenTW/react-emoji-search#19]
### What is this About?

Feature Request:
Addition of dark mode toggle button and storing the users preference in local storage so as to use the same theme that the user has set previously while loading the web app for the next time.

<br />

### Expected Behavior

The user would be able to toggle between different themes as per their preference
<br />

### Current Behavior

There is no such button

<br />

### Failure Information (for bugs)

<br />

### Steps to Reproduce

<br />

### Context

<br />

**Comment by SubhamKarmakar24** [comment]
@BraydenTW I would like to work on this issue as a part of Hacktoberfest 2021.

**Comment by BraydenTW** [comment]
Hey @SubhamKarmakar24! 👋🏼 

Thanks for doing taking the initiative to do this! Feel free to send over a PR whenever you're ready for me to take a look.

*Just one note: make sure it fits the overall neomorphic feeling! Thanks.*

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Hey @SubhamKarmakar24! 👋🏼
> 
> Thanks for doing taking the initiative to do this! Feel free to send over a PR whenever you're ready for me to take a look.
> 
> _Just one note: make sure it fits the overall neomorphic feeling! Thanks._

Sure, I will do it within a few days
