### ISSUE TITLE
Issue Generating template

### ISSUE THREAD

**Issue by sparkingdark** [BraydenTW/react-emoji-search#2]
**Title**:Give a appropriate title :smile: 

:arrow_down: 
**Description** :

Give Suitable description to the problem or your idea

**Link**:

Give any Link to the problem

:fireworks: :+1: :100:

**Comment by BraydenTW** [comment]
Good idea @sparkingdark! I'll get working on it :D

**Comment by sparkingdark** [comment]
If you need someone as maintainer I can work.

**Comment by BraydenTW** [comment]
Sorry, no. Maybe in a future project but I'd like to handle this one on my own.

Thanks for asking anyway :)

**Comment by sparkingdark** [comment]
That's awesome too...

**Comment by BraydenTW** [comment]
Just added the templates. Feel free to take a look :)
