### ISSUE TITLE
Scroll to the top button feature

### ISSUE THREAD

**Issue by harsh07bharvada** [BraydenTW/react-emoji-search#20]
### What is this About?

This is about a feature to add a scroll to the top button on the right bottom side

<br />

### Expected Behavior

When user clicks on the button the window view will reach at the top of the page

<br />

### Current Behavior

There is no such button at the moment

<br />

### Failure Information (for bugs)

<br />

### Steps to Reproduce

<br />

### Context

<br />

**Comment by harsh07bharvada** [comment]
👋 Hey @BraydenTW!
Thanks for this awesome tool. I would love to contribute and work on this enhancement as part of Hacktoberfest 2021. It would be kind if you could assign me this.

**Comment by BraydenTW** [comment]
Hey @harsh07bharvada! Thanks for showing interest. 

Yes, I think that this would be a great addition!

I am assigning you this now.

**Comment by khushali77** [comment]
Hey @BraydenTW, could you please confirm whether @harsh07bharvada is working on this or not still?
If not, could you please assign it to me?

**Comment by BraydenTW** [comment]
Sorry @khushali77! Forgot to close and resolve this issue.
