### ISSUE TITLE
Debouce in search bar

### ISSUE THREAD

**Issue by harsh07bharvada** [BraydenTW/react-emoji-search#22]
### What is this About?

This is a feature regarding adding debounce in the search bar

<br />

### Expected Behavior

Search and filter the list only after a certain delay to reduce search renders

<br />

### Current Behavior

The searched list gets rendered every time a new character is added or deleted

<br />

### Failure Information (for bugs)

<br />

### Steps to Reproduce

<br />

### Context

<br />

**Comment by harsh07bharvada** [comment]
Hey @BraydenTW
It would be kind if you could assign me this, I would love to work on this.

**Comment by BraydenTW** [comment]
Yes, that would be helpful. 

Thanks!

**Comment by BraydenTW** [comment]
Hey @harsh07bharvada, how is this going?

**Comment by pawankm21** [comment]
Hey, should the debounce take delay as an argument?

**Comment by BraydenTW** [comment]
@pawankm21 yes that would be great!

**Comment by pawankm21** [comment]
Added that.
