### ISSUE TITLE
[New Feature]: Add No Result Found UI 

### ISSUE THREAD

**Issue by faran4engg** [BraydenTW/react-emoji-search#26]
### What is this About?

A new feature to render correct UI when no results are found.

<br />

### Expected Behavior

Display no result found [ in the form of svg or a nice gif]

<br />

### Current Behavior

It renders blank UI

<br />

### Failure Information (for bugs)

<br />

### Steps to Reproduce

1. Type `abcd` in the search input
2. It renders blank UI

<br />

### Context

<br />

**Comment by faran4engg** [comment]
Hey @BraydenTW 
Could you please assign this issue to me ? I would like to implement this feature as a part of `hacktoberfest2021` :)

**Comment by BraydenTW** [comment]
Sure! Thanks.

**Comment by faran4engg** [comment]
> Sure! Thanks.

Raising PR in 10 minutes :)

**Comment by faran4engg** [comment]
> > Sure! Thanks.
> 
> Raising PR in 10 minutes :)

PR raised. Could you kindly add `hacktoberfest2021` label as well. 
Thanks in advance !
