### ISSUE TITLE
[New Feature] No search input UI

### ISSUE THREAD

**Issue by BraydenTW** [BraydenTW/react-emoji-search#28]
### What is this About?

A feature request for showing a UI piece for when the user hasn’t typed anything in the box. 

<br />

### Expected Behavior

The “Please type keywords in the box” UI will show when the user hasn’t typed anything. 

<br />

### Current Behavior

It is not implemented yet.

**Comment by BraydenTW** [comment]
@faran4engg

**Comment by faran4engg** [comment]
> @faran4engg would you like to take this on?

I would love to :)

**Comment by faran4engg** [comment]
> @faran4engg would you like to take this on?

Hey @BraydenTW , I have a question.
Currently, by default, it shows all the emojis. As a part of this ticket, we need to show “Please type keywords in the box” UI when we land on the home page for the first time. Is my understanding correct?

**Comment by BraydenTW** [comment]
@faran4engg - correct!

**Comment by faran4engg** [comment]
> @faran4engg - correct!

Awesome. Working on the fix !

**Comment by faran4engg** [comment]
> > @faran4engg - correct!
> 
> Awesome. Working on the fix !

PR https://github.com/BraydenTW/react-emoji-search/pull/33
