### ISSUE TITLE
Structutring The React project

### ISSUE THREAD

**Issue by sparkingdark** [BraydenTW/react-emoji-search#3]
I will be restructured the project for better navigation.

**Comment by BraydenTW** [comment]
Sounds good @sparkingdark. Submit a PR when you are ready.

**Comment by sparkingdark** [comment]
Always...

**Comment by sparkingdark** [comment]
@BraydenTW done with structuring you can check.

**Comment by BraydenTW** [comment]
@sparkingdark, looks great! I will merge it know.
