### ISSUE TITLE
"No result found" text is in black color in dark mode

### ISSUE THREAD

**Issue by SubhamKarmakar24** [BraydenTW/react-emoji-search#30]
### What is this About?
A bug that was generated due to #27 merged into main not taking into consideration the dark theme text colors. The "No results found" text is fine in light mode, but in dark mode, same colors were being used from the light mode, thus being difficult to read.

<br />

### Expected Behavior
Separate colors for light mode and dark mode.

<br />

### Current Behavior
Same color in both the modes

<br />

### Failure Information (for bugs)
The text color was hard-coded instead of being a variable(which can change dynamically depending on the current theme)

<br />

### Steps to Reproduce

<br />

### Context
The issue is due to absence of text color variable of the h2 tag used.

<br />

### Failure Logs
![Untitled](https://user-images.githubusercontent.com/50767716/135732226-676542ba-4e26-4630-a833-7a9c73ea7c9c.png)

This is the current condition in dark mode.

**Comment by faran4engg** [comment]
Nice one @SubhamKarmakar24 !
