### ISSUE TITLE
Add more common keywords to each emoji In data.json

### ISSUE THREAD

**Issue by zekehernandez** [BraydenTW/react-emoji-search#4]
Congrats on starting your journey with React. And what a fun, well executed project.

**Is your feature request related to a problem? Please describe.**
Sometimes, one might not know the exact name of an emoji.

**Describe the solution you'd like**
It could be nice to tag emojis with alternative names (behind the scenes), so that if someone searched for smile, the "grin" emoji would be included in the results. 

**Describe alternatives you've considered**

**Additional context**

**Comment by BraydenTW** [comment]
Very good points. I’ve been working on updating the `data.json` file with these keyword improvements. However it is a lot of work to do in a short amount of time so I added the **help wanted** label in order to get some extra helpers on this task.

**Comment by BraydenTW** [comment]
Hey @zekehernandez, I found a different open source JSON file with better keywords. I soon will open a PR for this.

Thanks again for pointing that out :)
